# Generated by Django 4.1 on 2023-04-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('ESTRELA', 'Estrela'), ('GALAXIA', 'Galáxia'), ('NEBULOSA', 'Nebulosa'), ('PLANETA', 'Planeta')], default='', max_length=50),
        ),
    ]
